config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcomes#index'

  resources :job_roles
  resources :workspaces
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :workspace, inverse_of: :person
  belongs_to :job_role, inverse_of: :person
  has_many :contacts
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true

  validates :description, presence: true
  validates :registration, presence: true, uniqueness: true, length: { is: 6 }, numericality: { only_integer: true }
  validates_uniqueness_of :job_role_id, :scope => [:workspace_id]
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_adm?
  before_action :set_person, only: %i[ show edit update destroy ]
  before_action :job_role_title, only: %i[index new create edit update]
  before_action :workspace_title, only: %i[index new create edit update]

  # GET /people or /people.json
  def index
    @people = Person.all
    @people = @people.where(("description like '%#{params[:search]}%'")).or(Person.where("cast(registration as text) like '%#{params[:search]}%'")) if params[:search].present?
    @people = @people.where(workspace_id: params[:search_workspace]) if params[:search_workspace].present?
    @people = @people.where(job_role_id: params[:search_job_role]) if params[:search_job_role].present?
    @people = @people.where(sex: params[:search_sex]) if params[:search_sex].present?
    @people = @people.order(:description)
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
      @contacts = Contact.where(person_id: params[:id]).paginate(page: params[:page], per_page: 5)
    end

    def job_role_title
      @job_role_title = JobRole.all.pluck(:title, :id)
    end

    def workspace_title
      @workspace_title = Workspace.all.pluck(:title, :id)
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:description, :registration, :birth_date, :birth_county, :birth_state, :marital_status, :sex, :workspace_id, :job_role_id,
      contacts_attributes: [:id, :telephone, :cell_phone, :email, :_destroy])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_contact_fields.html.erb
<div class="nested-fields">
  <div class="card">
    <h5 class="card-header">Contato</h5>
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-4">
          <%= f.label :telephone %>
          <%= f.text_field :telephone, placeholder: "Escreva seu Telefone", class: "form-control" %>
        </div>

        <div class="col-md-4">
          <%= f.label :cell_phone %>
          <%= f.text_field :cell_phone, placeholder: "Escreva seu Celular", class: "form-control" %>
        </div>

        <div class="col-md-4">
          <%= f.label :email %>
          <%= f.email_field :email, placeholder: "Escreva seu Email", class: "form-control" %>
        </div>

        <div class="col-md-12 mt-3">
          <%= link_to_remove_association 'Remover', f, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/_form.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <%= form_with(model: person, local: true) do |form| %>
        <% if person.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(person.errors.count, "error") %> Não é possível salvar essa pessoa por:</h2>

            <ul>
              <% person.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row g-3" style="margin-x:15px">
          <div class="col-md-4">
            <%= form.label :registration %>
            <%= form.text_field :registration, id: :person_registration, placeholder: "Escreva sua Matrícula", class: "form-control" %>
          </div>

          <div class="col-md-4">
            <%= form.label :description %>
            <%= form.text_field :description, id: :person_description, placeholder: "Escreva seu Nome", class: "form-control" %>
          </div>

          <div class="col-md-4">
            <%= form.label :birth_date %>
            <%= form.date_field :birth_date, id: :person_birth_date, class: "form-control" %>
          </div>

          <div class="col-md-3">
            <%= form.label :birth_county %>
            <%= form.text_field :birth_county, id: :person_birth_county, placeholder: "Escreva seu Município de Nascimento", class: "form-control" %>
          </div>

          <div class="col-md-3">
            <%= form.label :birth_state %>
            <%= form.text_field :birth_state, id: :person_birth_state, placeholder: "Escreva seu Estado de Nascimento", class: "form-control" %>
          </div>

          <div class="col-md-3">
            <%= form.label :marital_status %>
            <%= form.select(:marital_status, %w{ Solteiro(a) Casado(a) Divorciado(a) }, { include_blank: 'Selecione o Estado Civil' }, class: "form-select" ) %>
          </div>

          <div class="col-md-3">
            <%= form.label :sex %>
            <%= form.select(:sex, %w{ Masculino Feminino }, { include_blank: 'Selecione o Sexo' }, class: "form-select" ) %>
          </div>

          <div class="col-md-6">
            <%= form.label :workspace %>
            <%= form.select("workspace_id", @workspace_title, { include_blank: 'Selecione a Lotação' }, class: "form-control form-select" ) %>
          </div>

          <div class="col-md-6">
            <%= form.label :job_role %>
            <%= form.select("job_role_id", @job_role_title, { include_blank: 'Selecione o Cargo' }, class: "form-control form-select" ) %>
          </div>

          <div class="col-md-12 mt-3">
            <%= form.fields_for :contacts do |contact| %>
              <%= render partial: "contact_fields", locals: { f: contact } %>
            <% end %>
          </div>

          <div class="col-md-10 mt-3">
            <%= link_to_add_association 'Adicionar Contato', form, :contacts, class: "btn btn-success" %>
          </div>

          <div class="col-md-12 mt-3">
            <%= form.submit "Salvar", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<p id="notice"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Pessoas', people_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Edição</li>
  </ol>
</nav>

<h1 class="text-center">Editar Pessoa</h1>

<%= render 'form', person: @person %>

<%= link_to 'Voltar', people_path , class:  "btn btn-secondary", style: "margin-top:10px"%>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Pessoas</li>
  </ol>
</nav>

<div class="card">
  <h3 class="card-header">Pesquisar</h3>
  <div class="card-body">
    <%= form_tag(people_path, :method => :get) do %>
      <div class="row g-3">

        <div class="col-12">
          <%= text_field_tag 'search', nil, placeholder: 'Pesquisar por...', class: "form-control"%> 
        </div>

        <div class="col-md-4">
        <th><strong>Sexo</strong></th></br>
          <%= radio_button 'search_sex', nil, 'Masculino'%> Masculino <br/>
          <%= radio_button 'search_sex', nil, 'Feminino'%> Feminino <br/>
        </div>
        <br>

        <div class="col-md-4">
          <th><strong>Lotação</strong></th>
            <div>
              <%= select_tag 'search_workspace', options_for_select(@workspace_title.collect{ |u| [u[0], u[1]] }), {include_blank: 'Selecione a Lotação...', class:"form-select"}%>
            </div>
        </div>

        <div class="col-md-4">
          <th><strong>Cargo</strong></th> 
            <div>
              <%= select_tag 'search_job_role', options_for_select(@job_role_title.collect{ |u| [u[0], u[1]] }), {include_blank: 'Selecione o Cargo...', class: "form-select"}%>
            </div>
        </div> 
        <% if authenticate_adm? %>
          <div class="col-md-11">
            <%= link_to "Nova Pessoa", new_person_path, class: "btn btn-success" %>
          </div>
        <% end %>
        
        <div class="col">
          <%= submit_tag "Filtrar", class:  "btn btn-primary"%>
        </div>

      </div>
    <% end %>
  </div>
</div>


<table class = "table table-striped table-bordered" style="margin-top:15px">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Data Nascimento</th>
      <th>Sexo</th>
      <th>Lotação</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.description %></td>
        <td><%= person.registration %></td>
        <td><%= person.birth_date %></td>
        <td><%= person.sex %></td>
        <td><%= person.workspace.title %></td>
        <td><%= person.job_role.title %></td>
        <td><%= link_to fa_icon("eye"), person %></td>
        <td><%= link_to fa_icon("edit"), edit_person_path(person) if authenticate_adm? %></td>
        <td><%= link_to fa_icon("trash"), person, method: :delete, data: { confirm: 'Tem certeza?' } if authenticate_adm?%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Pessoas', people_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Cadastro</li>
  </ol>
</nav>

<h1 class="text-center">Cadastrar Pessoa</h1>

  <%= render 'form', person: @person %>

  <%= link_to 'Voltar', people_path, class: "btn btn-secondary", style: "margin-top:10px" %>

app/views/people/show.html.erb
<div class="container mt-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
      <li class="breadcrumb-item"><%= link_to 'Pessoas', people_path %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @person.description %></li>
    </ol>
  </nav>

  <p id="notice" class="alert alert-info"><%= notice %></p>

  <div class="card">
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-3">
          <p><strong>Matricula:</strong> <%= @person.registration %></p>
        </div>
        <div class="col-md-3">
          <p><strong>Nome:</strong> <%= @person.description %></p>
        </div>
        <div class="col-md-3">
          <p><strong>Data Nascimento:</strong> <%= @person.birth_date %></p>
        </div>
        <div class="col-md-3">
          <p><strong>Município de Nascimento:</strong> <%= @person.birth_county %></p>
        </div>
        <div class="col-md-3">
          <p><strong>Estado de Nascimento:</strong> <%= @person.birth_state %></p>
        </div>
        <div class="col-md-3">
          <p><strong>Estado Civil:</strong> <%= @person.marital_status %></p>
        </div>
        <div class="col-md-6">
          <p><strong>Sexo:</strong> <%= @person.sex %></p>
        </div>
        <div class="col-md-3">
          <p><strong>Lotação:</strong> <%= @person.workspace.title %></p>
        </div>
        <div class="col-md-9">
          <p><strong>Cargo:</strong> <%= @person.job_role.title %></p>
        </div>

        <% if @contacts.any? %>
          <div class="card col-md-12 mt-3">
            <div class="card-header">Contatos</div>
            <% @contacts.each do |contact| %>
              <div class="card-body">
                <div class="row g-3">
                  <div class="col-md-4">
                    <p><strong>Telefone:</strong> <%= contact.telephone %></p>
                  </div>
                  <div class="col-md-4">
                    <p><strong>Celular:</strong> <%= contact.cell_phone %></p>
                  </div>
                  <div class="col-md-4">
                    <p><strong>Email:</strong> <%= contact.email %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="col-md-9">
          <%= link_to 'Voltar', people_path, class: "btn btn-secondary mt-3" %>
        </div>
        <div class="col">
          <%= link_to 'Excluir', @people, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger mt-3" if authenticate_adm? %>
        </div>
        <div class="col">
          <%= link_to 'Editar', edit_person_path(@person), class: "btn btn-primary mt-3" if authenticate_adm? %>
        </div>
      </div>
    </div>
  </div>
</div>