config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcomes#index'

  resources :job_roles
  resources :workspaces
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workspace.rb
class Workspace < ApplicationRecord
    has_many :person
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_adm?
  before_action :set_workspace, only: %i[ show edit update destroy ]

  # GET /workspaces or /workspaces.json
  def index
    @workspaces = Workspace.all
  end

  # GET /workspaces/1 or /workspaces/1.json
  def show
  end

  # GET /workspaces/new
  def new
    @workspace = Workspace.new
  end

  # GET /workspaces/1/edit
  def edit
  end

  # POST /workspaces or /workspaces.json
  def create
    @workspace = Workspace.new(workspace_params)

    respond_to do |format|
      if @workspace.save
        format.html { redirect_to @workspace, notice: "Workspace was successfully created." }
        format.json { render :show, status: :created, location: @workspace }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workspaces/1 or /workspaces/1.json
  def update
    respond_to do |format|
      if @workspace.update(workspace_params)
        format.html { redirect_to @workspace, notice: "Workspace was successfully updated." }
        format.json { render :show, status: :ok, location: @workspace }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workspaces/1 or /workspaces/1.json
  def destroy
    @workspace.destroy
    respond_to do |format|
      format.html { redirect_to workspaces_url, notice: "Workspace was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workspace
      @workspace = Workspace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workspace_params
      params.require(:workspace).permit(:title)
    end
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/workspaces/_form.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <%= form_with(model: workspace, local: true) do |form| %>
        <% if workspace.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(workspace.errors.count, "error") %> prohibited this workspace from being saved:</h2>
            <ul>
              <% workspace.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, id: :workspace_title, class: 'form-control' %>
        </div>

        <div class="form-actions">
          <%= form.submit 'Save', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/workspaces/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Lotação', workspaces_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Editar</li>
  </ol>
</nav>

<h1>Editing Workspace</h1>

<%= render 'form', workspace: @workspace %>

<%= link_to 'Show', @workspace %> |
<%= link_to 'Back', workspaces_path %>

app/views/workspaces/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
          <li class="breadcrumb-item active" aria-current="page">Lotação</li>
        </ol>
      </nav>

      <h1 class="mb-3">Workspaces</h1>

      <table class="table">
        <thead>
        <tr>
          <th>Workspace</th>
          <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @workspaces.each do |workspace| %>
          <tr>
            <td><%= workspace.title %></td>
            <td>
              <%= link_to 'Show', workspace, class: 'btn btn-primary btn-sm mr-2' %>
              <%= link_to 'Edit', edit_workspace_path(workspace), class: 'btn btn-info btn-sm mr-2' %>
              <%= link_to 'Destroy', workspace, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <%= link_to 'New Workspace', new_workspace_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/workspaces/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Lotação', workspaces_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Novo</li>
  </ol>
</nav>

<h1>New Workspace</h1>

<%= render 'form', workspace: @workspace %>

<%= link_to 'Back', workspaces_path %>

app/views/workspaces/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <p class="alert alert-info"><%= notice %></p>

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
          <li class="breadcrumb-item"><%= link_to 'Lotação', workspaces_path %></li>
          <li class="breadcrumb-item active" aria-current="page"><%= @workspace.title %></li>
        </ol>
      </nav>

      <p>
        <strong>Title:</strong>
        <%= @workspace.title %>
      </p>

      <%= link_to 'Edit', edit_workspace_path(@workspace), class: 'btn btn-primary' %> |
      <%= link_to 'Back', workspaces_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>