config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcomes#index'

  resources :job_roles
  resources :workspaces
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_welcome, only: %i[ show edit update destroy ]

  # GET /welcomes or /welcomes.json
  def index
    
  end

  # GET /welcomes/1 or /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes or /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: "Welcome was successfully created." }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1 or /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: "Welcome was successfully updated." }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1 or /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: "Welcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form.html.erb
<%= simple_form_for(@welcome) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- ... Your head content ... -->
</head>
<body>
<div class="container">
  <div class="mt-3">
    <!-- ... Alerts ... -->
  </div>

  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <!-- ... Navbar content ... -->
  </nav>

  <div class="container">
    <h1 class="mb-4">Bem-vindo!!!</h1>

    <%= link_to 'Pessoas', people_path, class: "btn btn-primary mr-2" %>

    <% if authenticate_adm? %>
      <%= link_to 'Lotações', workspaces_path, class: "btn btn-secondary mr-2" %>
      <%= link_to 'Cargos', job_roles_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

<!-- ... Your scripts ... -->
</body>
</html>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>